flutter_application_id:
  android:
    id: "io.github.creatorbe.stocky"
    name: "Stocky"
    gradle_file: "android/app/build.gradle"
  ios:
    id: "io.github.creatorbe.stocky"
    name: "Stocky"